apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-home
  template:
    metadata:
      labels:
        app: nginx-home
    spec:
      containers:
      - name: nginx-home
        image: nginx-home-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000